2023-07-31 03:45:51,318 - ERROR - Query error: (psycopg2.errors.ActiveSqlTransaction) DROP DATABASE cannot run inside a transaction block

[SQL: DROP DATABASE IF EXISTS db_post_beta]
(Background on this error at: https://sqlalche.me/e/14/2j85)
2023-07-31 03:47:32,588 - ERROR - Query error: (psycopg2.errors.ActiveSqlTransaction) DROP DATABASE cannot run inside a transaction block

[SQL: DROP DATABASE IF EXISTS db_post_beta]
(Background on this error at: https://sqlalche.me/e/14/2j85)
2023-07-31 03:48:45,239 - ERROR - Query error: (psycopg2.errors.ActiveSqlTransaction) DROP DATABASE cannot run inside a transaction block

[SQL: DROP DATABASE IF EXISTS db_post_beta]
(Background on this error at: https://sqlalche.me/e/14/2j85)
2023-07-31 03:51:33,204 - ERROR - Query error: (psycopg2.errors.ActiveSqlTransaction) DROP DATABASE cannot run inside a transaction block

[SQL: DROP DATABASE IF EXISTS db_post_beta]
(Background on this error at: https://sqlalche.me/e/14/2j85)
2023-11-22 21:32:40,797 - ERROR - Connection error: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-11-22 21:32:40,846 - ERROR - Connection error: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-11-22 21:32:54,955 - ERROR - Connection error: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-11-23 18:31:24,899 - ERROR - Connection error: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-11-23 18:31:24,939 - ERROR - Connection error: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-11-23 18:31:25,744 - ERROR - Connection error: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-11-27 01:47:37,319 - ERROR - Connection error: (pymysql.err.OperationalError) (1049, "Unknown database 'db_beta'")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-11-27 01:47:42,755 - ERROR - Connection error: (pymysql.err.OperationalError) (1049, "Unknown database 'db_beta'")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-12-05 16:28:57,991 - ERROR - Connection error: (pymysql.err.OperationalError) (1049, "Unknown database 'db_beta'")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
